//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by vncviewer.rc
//
#define IDR_MANIFEST                    1
#define IDI_ICON                        101
#define IDD_VNC_AUTH_DLG                102
#define IDD_CONNECTING_DLG              103
#define IDD_CONNECTION_DLG              104
#define IDC_DOT_CURSOR                  105
#define IDD_ABOUT                       107
#define IDD_FORMAT                      108
#define IDD_MISC                        109
#define IDD_INPUTS                      110
#define IDD_SERVER_KEYS                 111
#define IDR_TRAY                        112
#define IDD_CONNECTION_INFO             113
#define IDD_DEFAULTS                    116
#define IDB_BITMAP                      120
#define IDD_FILETRANSFER_DLG            121
#define IDB_TOOLBAR                     122
#define IDD_FTCONFIRM_DLG               124
#define IDI_FTUP                        125
#define IDI_FTDIR                       126
#define IDI_FTFILE                      127
#define IDI_FTRELOAD                    128
#define IDR_FTMENU                      130
#define IDD_FTCANCELING                 131
#define IDD_FTCREATEFOLDER              132
#define IDD_FTBROWSE                    133
#define IDC_PASSWORD                    1000
#define IDC_CONNECTING_TEXT             1001
#define IDC_SERVER_EDIT                 1002
#define IDC_USERNAME                    1005
#define IDC_VERSION                     1008
#define IDC_BUILDTIME                   1009
#define IDC_ENCODING_AUTO               1010
#define IDC_FORMAT_FULLCOLOUR           1011
#define IDC_ENCODING_ZRLE               1012
#define IDC_ENCODING_HEXTILE            1013
#define IDC_CONN_SHARED                 1013
#define IDC_ENCODING_RAW                1014
#define IDC_FULL_SCREEN                 1014
#define IDC_SEND_POINTER                1015
#define IDC_SEND_KEYS                   1016
#define IDC_CLIENT_CUTTEXT              1017
#define IDC_SERVER_CUTTEXT              1018
#define IDC_LOCAL_CURSOR                1019
#define IDC_DESKTOP_RESIZE              1020
#define IDC_COPYRIGHT                   1021
#define IDC_DESCRIPTION                 1022
#define IDC_OPTIONS                     1023
#define IDC_ABOUT                       1024
#define IDC_LIST1                       1025
#define IDC_FTLOCALLIST                 1025
#define IDC_INFO_NAME                   1026
#define IDC_INFO_HOST                   1027
#define IDC_INFO_SIZE                   1028
#define IDC_INFO_PF                     1029
#define IDC_INFO_DEF_PF                 1030
#define IDC_INFO_LINESPEED              1031
#define IDC_INFO_VERSION                1032
#define IDC_PROTOCOL_3_3                1034
#define IDC_ACCEPT_BELL                 1035
#define IDC_FORMAT_VERYLOWCOLOUR        1036
#define IDC_SHOW_TOOLBAR                1036
#define IDC_FORMAT_LOWCOLOUR            1037
#define IDC_FORMAT_MEDIUMCOLOUR         1038
#define IDC_LOAD_DEFAULTS               1040
#define IDC_SAVE_DEFAULTS               1041
#define IDC_LOAD_CONFIG                 1042
#define IDC_EMULATE3                    1043
#define IDC_POINTER_INTERVAL            1044
#define IDC_SAVE_CONFIG                 1045
#define IDC_INFO_SECURITY               1046
#define IDC_SAVE_CONFIG_AS              1048
#define IDC_MENU_KEY                    1051
#define IDC_REQUESTED_ENCODING          1052
#define IDC_LAST_ENCODING               1053
#define IDC_SECURITY_LEVEL              1054
#define IDC_INFO_ENCRYPTION             1055
#define IDC_AUTO_RECONNECT              1056
#define IDC_DISABLE_WINKEYS             1057
#define IDC_QUALITYLEVEL                1058
#define IDC_FTLOCALUP                   1058
#define IDC_SEND_SYSKEYS                1059
#define IDC_FTLOCALBROWSE               1059
#define IDC_FTREMOTERELOAD              1060
#define IDC_FTREMOTEUP                  1061
#define IDC_FTREMOTEBROWSE              1062
#define IDC_FTPROGRESS                  1063
#define IDC_FTGENERALPROGRESS           1063
#define IDC_PROGRESS                    1064
#define IDC_FTSINGLEPROGRESS            1064
#define IDC_FTSTATUS                    1065
#define IDC_FTCURRENTPROCENT            1066
#define IDC_FTSINGLEPERCENT             1066
#define IDC_FTTOTALPROCENT              1067
#define IDC_FTGENERALPERCENT            1067
#define IDC_FTUPLOAD                    1072
#define IDC_FTCANCEL                    1073
#define IDC_FTDOWNLOAD                  1074
#define IDC_FTCLOSE                     1075
#define IDC_FTLOCALLABEL                1076
#define IDC_FTREMOTELABEL               1077
#define IDC_FTDIRNAME                   1078
#define IDC_CONFIRM_YESTOALL            1079
#define IDC_CONFIRM_TEXT                1080
#define IDC_EDIT2                       1082
#define IDC_FTFOLDERNAME                1083
#define IDC_FTTEXT                      1084
#define IDC_FTBROWSEPATH                1085
#define IDC_FTBROWSETREE                1086
#define IDC_TYPE                        1088
#define IDC_ENCODING_TIGHT              1089
#define IDC_FTLOCALPATH                 1090
#define IDC_CUSTOM_COMPRESSLEVEL        1091
#define IDC_FTREMOTEPATH                1092
#define IDC_COMPRESSLEVEL               1093
#define IDC_FTREMOTELIST                1094
#define IDC_ALLOW_JPEG                  1095
#define IDC_FTLOCALRELOAD               1096
#define IDC_STATIC_SCALE                1097
#define IDC_COMBO_SCALE                 1098
#define IDC_STATIC_PERCENT              1099
#define ID_TOOLBAR                      40002
#define ID_CLOSE                        40003
#define ID_OPTIONS                      40004
#define ID_NEW_CONNECTION               40005
#define ID_ABOUT                        40006
#define ID_FULLSCREEN                   40007
#define ID_SEND_CAD                     40008
#define ID_INFO                         40009
#define ID_REQUEST_REFRESH              40010
#define ID_CTRL_KEY                     40011
#define ID_ALT_KEY                      40012
#define ID_SEND_MENU_KEY                40013
#define ID_SEND_CTLESC                  40014
#define ID_CONN_SAVE_AS                 40015
#define ID_FILE_TRANSFER                40016
#define ID_ZOOM_IN                      40017
#define ID_ZOOM_OUT                     40018
#define ID_ACTUAL_SIZE                  40019
#define ID_AUTO_SIZE                    40020
#define IDM_FTCOPY                      40022
#define IDM_FTRENAME                    40023
#define IDM_FTDELETE                    40024
#define IDM_FTCANCEL                    40025
#define IDM_FTCREATEFOLDER              40026
#define IDM_SHOW_TOOLBAR                40027

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         40028
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
