.TH X0VNCSERVER 1 "January  7, 2008" "TightVNC" "TightVNC Manual"
.SH NAME
x0vncserver \- TightVNC Server for real X displays
.SH SYNOPSIS
.B x0vncserver
.RI [ options ]
.SH DESCRIPTION
.B x0vncserver
is a TightVNC Server which makes any X display remotely accessible via VNC,
TightVNC or compatible viewers. Unlike Xvnc, it does not create a virtual
display. Instead, it just shares an existing X server (typically, that one
connected to the physical screen).
.SH OPTIONS
.B x0vncserver
interprets the command line as a list of parameters with optional values.
Running \fBx0vncserver -h\fP will show a list of all valid parameters with
short descriptions. All parameters are optional, but normally you would have
to use the \fBPasswordFile\fP parameter.
.PP
There are several forms of specifying parameters in the command line (here we
use `\fISomeParameter\fP' as an example parameter name):
.TP
.B -\fISomeParameter\fP
Enable the parameter, turn the feature on. This form can be used with
parameters that simply enable or disable some feature.
.TP
.B -\fISomeParameter\fP=0
Disable the parameter, turn the feature off.
.TP
.B -\fISomeParameter\fP=\fIvalue\fP
Assign the specified \fIvalue\fP to the parameter. The leading dash can be
omitted, or it can be doubled if desired (like in GNU-style long
options). The equality sign is optional so it can be replaced by spaces.
.PP
Parameter names are case-insensitive, their order in the command line can be
arbitrary.
.SH SEE ALSO
.BR Xvnc (1),
.BR vncpasswd (1),
.br
http://www.tightvnc.com/
.SH AUTHOR
This manual page was written by Constantin Kaplinsky.
