#!/bin/sh
# This script wraps build-xorg-7.4 to enable building a version of TigerVNC
# which is compatible across Linux distributions.

set -e

if [ "$1" = "" ]; then
	echo USAGE: $0  init \| build \| update
	exit 0
fi

SCRIPTDIR=`dirname $0`
pushd $SCRIPTDIR/../unix
if [ ! -d ./xorg.build/syslib ]; then
	mkdir -p ./xorg.build/syslib
fi
CFLAGS='-O3 -static-libgcc'
CXXFLAGS=$CFLAGS
LDFLAGS=$CFLAGS' -L'`pwd`'/xorg.build/syslib'
export CFLAGS
export CXXFLAGS
export LDFLAGS
if [ -f ./xorg.build/syslib/libstdc++.a ]; then
	rm -f ./xorg.build/syslib/libstdc++.a
fi
ln -fs `gcc $CFLAGS -print-file-name=libstdc++.a` ./xorg.build/syslib
if [ -f ./xorg.build/syslib/libcrypto.a ]; then
	rm -f ./xorg.build/syslib/libcrypto.a
fi
if [ -f ./xorg.build/syslib/libz.a ]; then
	rm -f ./xorg.build/syslib/libz.a
fi
if [ "`uname -m`" = "x86_64" ]; then
	ln -fs /usr/lib64/libcrypto.a ./xorg.build/syslib
	ln -fs /usr/lib64/libz.a ./xorg.build/syslib
else
	ln -fs /usr/lib/libcrypto.a ./xorg.build/syslib
	ln -fs /usr/lib/libz.a ./xorg.build/syslib	
fi
. build-xorg-7.4 $1 -static
popd
