#!/bin/sh
# This script builds a 32-bit version of TigerVNC on OS/X 10.4 or later.  The
# resulting version of TigerVNC is not backward compatible.

set -e

SCRIPTDIR=`dirname $0`
pushd $SCRIPTDIR/..
CFLAGS='-O3 -m32'
CXXFLAGS=$CFLAGS
LDFLAGS=$CFLAGS
export CFLAGS CXXFLAGS LDFLAGS
if [ ! -f ./configure ]; then
    autoreconf -fiv
fi
configure
make
popd
