#!/bin/sh
# This script builds a version of TigerVNC on OS/X 10.5 or later which is
# compatible with OS/X 10.4 or later.  The OS/X 10.4 compatibility SDK (part
# of XCode) must be installed.

set -e

SCRIPTDIR=`dirname $0`
pushd $SCRIPTDIR/..
CC=gcc-4.0
CXX=g++-4.0
CPP=cpp-4.0
CFLAGS='-isysroot /Developer/SDKs/MacOSX10.4u.sdk -mmacosx-version-min=10.4 -O3 -m32'
CXXFLAGS=$CFLAGS
LDFLAGS=$CFLAGS
CPPFLAGS=$CFLAGS
export CFLAGS CXXFLAGS LDFLAGS CPPFLAGS CC CXX CPP
if [ ! -f ./configure ]; then
    autoreconf -fiv
fi
configure --x-libraries=/usr/X11R6/lib/
make
popd
