#!/bin/sh
# This script builds a 64-bit version of TigerVNC on OS/X 10.6 or later.
# NASM 2.07 or later from MacPorts must be installed in /opt/local.

set -e

SCRIPTDIR=`dirname $0`
pushd $SCRIPTDIR/..
CFLAGS='-O3'
CXXFLAGS=$CFLAGS
export CFLAGS CXXFLAGS
if [ ! -f ./configure ]; then
    autoreconf -fiv
fi
configure --host=x86_64-apple-darwin10.0.0 NASM=/opt/local/bin/nasm
make
popd
